name: sembast_client_dart
description: A CLI client for basic manipulation of sembast database files
version: 1.0.1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  console: ^4.1.0
  dcli: ^1.36.0
  crypto: ^3.0.2
  encrypt: ^5.0.1
  fpdart: ^0.4.0
  get_it: ^7.2.0
  sembast: ^3.3.1

dev_dependencies:
  lints: ^2.0.1
