name: "main"
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  armcompile:
    name: Compile for arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v2
      - run: |
          docker run --rm \
            --platform linux/arm64 \
            --volume "$PWD:$PWD" \
            --workdir "$PWD" \
            docker.io/library/dart:latest \
            /bin/sh -c "mkdir armlinux && dart pub get && dart compile exe bin/main.dart -o armlinux/sembast_cli_linuxarm64"
      - run: ls -l armlinux
      - uses: actions/upload-artifact@v2
        with:
          name: sembast_cli_linuxarm64
          path: armlinux

  armrelease:
    needs: armcompile
    name: Release to Repository for arm64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: sembast_cli_linuxarm64
          path: armlinux
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: bin-*/*
